Calculate business day intervals
DaneWeber/MaintenanceApp pull request #11
Opened 2017-07-27 17:59 UTC by DaneWeber

I'm starting this PR even though this first commit doesn't introduce any functionality. I'll add commits to this branch as I proceed.

2017-07-27 20:26 UTC, DaneWeber commented
At this point it's working, mostly, but I need to configure the `business_time` gem because it's working on UTC time and has limited working hours.

2017-07-28 18:58 UTC, DaneWeber commented
@jacohen10 - this is ready for review.

I rebased and had to resolve conflicts. I'm not completely clear how a set of my commits are repeated for this.

2017-07-31 17:56 UTC, jacohen10 requested changes

2017-07-31 17:56 UTC, jacohen10 commented on app/models/chore.rb
> +    case
can you split this case statement into it's own function. Also, what's the reasoning for returning false and true?

2017-07-31 17:56 UTC, jacohen10 commented on app/models/chore.rb
> +    start_date += 1 if start_date.wday == 6
what is wday and divmod?

2017-07-31 17:56 UTC, jacohen10 commented on test/models/chore_test.rb
we should go through these tests together

2017-07-31 18:25 UTC, DaneWeber commented on app/models/chore.rb
> +    start_date += 1 if start_date.wday == 6
`wday` is a method for the `Date` class that returns the weekday of a given date:
https://ruby-doc.org/stdlib-2.3.1/libdoc/date/rdoc/Date.html#method-i-wday

`divmod` is a method for the `Numeric` class that returns the quotient and remainder as an array:
https://ruby-doc.org/core-2.3.0/Numeric.html#method-i-divmod

2017-07-31 18:25 UTC, DaneWeber commented on app/models/chore.rb
> +    case
What's the purpose of moving the `case` statement into its own function? While I will certainly do so, and have ideas for where to divide responsibility, I'm not sure what benefit you're aiming for, and thus not sure if I'll be achieving it.

Regarding returning `true` and `false`, I did that essentially as a debug step. Upon reflection, I should probably pull that out.

2017-07-31 18:25 UTC, DaneWeber commented on app/models/chore.rb
> +  enum interval_type: { calendar_days: 0, business_days: 1 }
@jacohen10  - `enum` defines the `.calendar_days?` and `.business_days` methods.

2017-07-31 18:25 UTC, DaneWeber commented on app/models/chore.rb
> +  enum interval_type: { calendar_days: 0, business_days: 1 }
http://api.rubyonrails.org/classes/ActiveRecord/Enum.html

2017-07-31 18:33 UTC, DaneWeber commented on test/models/chore_test.rb
Scheduled for tomorrow.

2017-07-31 21:40 UTC, DaneWeber commented on app/models/chore.rb
> +    case
Updated. Please re-review @jacohen10

2017-08-02 13:17 UTC, DaneWeber commented
I'm going to create a new PR for the change to the `add_business_days` function.

2017-08-02 13:17 UTC, merged